x-railsapp: &default-rails
  build:
    context: .
    args:
      - APP_USER_UID=${UID}
      - APP_GROUP_GID=${GID}
      - RUBY_VERSION=${RUBY_VERSION}
  user: "${UID}:${GID}"
  env_file:
    - '.env'
  tty: true
  stdin_open: true
  volumes:
    - '.:/app:cached'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  website:
    <<: *default-rails
    depends_on:
      - db
      - webpack
    environment:
      DATABASE_URL: postgres://postgres:password@db/ruby_lovers_development
      WAIT_HOSTS: postgres:5432
    ports:
      - "127.0.0.1:${RAILS_SERVER_PORT:-5000}:${RAILS_SERVER_PORT:-5000}"
    command: bash -c 'rm -f /app/tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p ${RAILS_SERVER_PORT:-5000}'
  webpack:
    <<: *default-rails
    command: 'bash -c "yarn && ./bin/webpack"'
